baseURL = "https://techwithomid.ir/"
languageCode = "fa"
DefaultContentLanguage = "en"


title = "تک ویت امید"
author = "Omid"
theme = "paper"

[params]
  color = "linen"

  github = "techwithomid"
  instagram = "techwithomidjq"

#  name = "امید"
#  bio = "دست نوشته های یک برنامه نویس"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "درباره‌من"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "تماس با من"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
