baseURL = "https://techwithomid.ir"
languageCode = "fa"
DefaultContentLanguage = "fa"


title = "تک ویت امید"
author = "Omid"
theme = "paper-rtl"
paginate = 10
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS"]

[params]
  color = "linen"
    
  avatar = 'omidmmadi@gmail.com'
  name = "امید"
  bio = "دست نوشته های یک برنامه نویس"

  github = "techwithomid"
  instagram = "techwithomid"

  graphcommentId = "techwithomid"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "درباره‌من"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "تماس با من"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
